let
    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
    #"DNOPRODUCE-PROD" = Source{[Name=EnvName]}[Data],
    #"DNO Inc. LIVE" = #"DNOPRODUCE-PROD"{[Name=CompanyName]}[Data],
    Advanced = #"DNO Inc. LIVE"{[Name="Advanced"]}[Data],
    #"dnopowerbi/dnopowerbireports/v1.0" = Advanced{[Name=API]}[Data],
    valueEntry_table = #"dnopowerbi/dnopowerbireports/v1.0"{[Name="valueEntry", Signature="table"]}[Data],
    #"Removed Other Columns" = Table.SelectColumns(
        valueEntry_table,
        {
            "entryNo",
            "costAmountActual",
            "documentNo",
            "documentType",
            "itemLedgerEntryType",
            "postingDate",
            "salesAmountActual",
            "sourceNo",
            "sourceType",
            "variantCode",
            "customer"
        }
    ),
    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([sourceType] = "Customer")),

    //Define Function to Insert Spaces Before Uppercase ---
    InsertSpaceBeforeUpper = (input as text) as text =>
        let
            length = Text.Length(input),
            indices = {0..(length - 1)},
            listChars = List.Transform(
                indices,
                (i) =>
                    let
                        current = Text.At(input, i),
                        previous = if i > 0 then Text.At(input, i - 1) else ""
                    in
                        if i > 0 and previous = Text.Lower(previous) and current = Text.Upper(current)
                        then " " & current
                        else current
            )
        in
            Text.Combine(listChars, ""),

    //Auto-Rename Columns with Proper Spacing ---
    RenamedColumns = Table.RenameColumns(
        #"Filtered Rows",
        List.Transform(
            Table.ColumnNames(#"Filtered Rows"),
            (colName) => { colName, Text.Proper(InsertSpaceBeforeUpper(colName)) }
        )
    ),

    //Output Final Table ---
    FinalOutput = RenamedColumns
in
    FinalOutput

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
let
    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
    PRODUCTION = Source{[Name=EnvName]}[Data],
    #"ETEC Inc." = PRODUCTION{[Name=CompanyName]}[Data],
    Advanced = #"ETEC Inc."{[Name="Advanced"]}[Data],
    #"pbinew/powerbireports/v1.0" = Advanced{[Name=API]}[Data],
    item_table = #"pbinew/powerbireports/v1.0"{[Name="item", Signature="table"]}[Data],
    #"Removed Other Columns1" = Table.SelectColumns(item_table,{"no", "baseUnitOfMeasure", "description", "description2", "itemCategoryCode"}),

    //Function to insert space before uppercase letters ---
    InsertSpaceBeforeUpper = (input as text) as text =>
        let
            length = Text.Length(input),
            indices = {0..(length - 1)},
            listChars = List.Transform(
                indices,
                (i) =>
                    let
                        current = Text.At(input, i),
                        previous = if i > 0 then Text.At(input, i - 1) else ""
                    in
                        if i > 0 and previous = Text.Lower(previous) and current = Text.Upper(current) then " " & current
                        else current
            )
        in
            Text.Combine(listChars, ""),

    //Rename all columns with proper spacing ---
    RenamedColumns = Table.RenameColumns(
        #"Removed Other Columns1",
        List.Transform(
            Table.ColumnNames(#"Removed Other Columns1"),
            (colName) => { colName, Text.Proper(InsertSpaceBeforeUpper(colName)) }
        )
    ),

    //Minor Column Renaming (optional) ---
    #"Renamed Columns" = Table.RenameColumns(
        RenamedColumns,
        {
            {"No", "Item No"}
        },
        MissingField.Ignore
    ),

    //Return final output ---
    FinalOutput = #"Renamed Columns"
in
    FinalOutput
