let
    Source = Dynamics365BusinessCentral.ApiContentsWithOptions(null, null, null, null),
    PRODUCTION = Source{[Name=EnvName]}[Data],
    #"ETEC Inc." = PRODUCTION{[Name=CompanyName]}[Data],
    Advanced = #"ETEC Inc."{[Name="Advanced"]}[Data],
    #"pbinew/powerbireports/v1.0" = Advanced{[Name=API]}[Data],
    item_table = #"pbinew/powerbireports/v1.0"{[Name="item", Signature="table"]}[Data],
    #"Removed Other Columns1" = Table.SelectColumns(item_table,{"no", "baseUnitOfMeasure", "description", "description2", "itemCategoryCode"}),

    //Function to insert space before uppercase letters ---
    InsertSpaceBeforeUpper = (input as text) as text =>
        let
            length = Text.Length(input),
            indices = {0..(length - 1)},
            listChars = List.Transform(
                indices,
                (i) =>
                    let
                        current = Text.At(input, i),
                        previous = if i > 0 then Text.At(input, i - 1) else ""
                    in
                        if i > 0 and previous = Text.Lower(previous) and current = Text.Upper(current) then " " & current
                        else current
            )
        in
            Text.Combine(listChars, ""),

    //Rename all columns with proper spacing ---
    RenamedColumns = Table.RenameColumns(
        #"Removed Other Columns1",
        List.Transform(
            Table.ColumnNames(#"Removed Other Columns1"),
            (colName) => { colName, Text.Proper(InsertSpaceBeforeUpper(colName)) }
        )
    ),

    //Minor Column Renaming (optional) ---
    #"Renamed Columns" = Table.RenameColumns(
        RenamedColumns,
        {
            {"No", "Item No"}
        },
        MissingField.Ignore
    ),

    //Return final output ---
    FinalOutput = #"Renamed Columns"
in
    FinalOutput
